Objetivo 0 [IV-22-23]
Gundisalvus2/Wind-of-change pull request #1
Opened 2022-09-21 09:45 UTC by Gundisalvus2

2022-09-22 10:48 UTC, Gundisalvus2 commented
* [X] ¿Se trata de un problema real del que se tenga conocimiento personal?
* [X] ¿Se trata de un problema que para solucionar requiera el despliegue
   de una aplicación en la nube?
* [X] ¿La solución requiere una cierta cantidad de lógica de negocio, en vez
    solucionarse sólo almacenando y buscando?
      Sí, además de almacenar información, ha de realizar cálculos para tratar de optimizar tanto el espacio disponible en 
      almacén como la compra de materias primas.
* [X] ¿Se ha incluído la configuración del repositorio y se ha enlazado desde el `README`?
       Sí, al final del documento.

2022-09-24 08:45 UTC, JJ commented
La lista de comprobación tiene que estar en el cuerpo.

2022-09-24 08:49 UTC, JJ requested changes
Las soluciones propuestas no tienen nada que ver con el problema, y tampoco tienen una lógica de negocio más aqllá de "estadísticas".
Se pide que propongáis soluciones para que, a través de tests automáticos, se pueda averiguar si el procesamiento de datos propuesto lo soluciona o no.
Tampoco es esto lo que hablamos en clase, donde me pareció entender que querías hacer predicción (con todos los problemas que esto conlleva, también)

2022-09-24 08:49 UTC, JJ commented on README.md
> +A raíz de las noticias de este pasado verano donde se exponía la mala situación de los bancos de alimentos, que sufrían desabastecimiento de frutas y excedente de alimentos no perecederos tales como
Los problemas físicos se resuelven muy mal con aplicaciones informáticas. Por favor, lee en el guión qué tipo de problemas suelen ser más adecuados.

2022-09-24 08:49 UTC, JJ commented on README.md
> +- Estadísticas de proveedores. Para ayudar al trabajador a elegir el proveedor en función de las necesidades de la empresa; p. ej: El más barato o el más rápido en función de la urgencia que haya por
¿De qué forma resuelve esto el problema?

2022-09-24 08:49 UTC, JJ commented on README.md
> +- Un consumo medio de las materias por época del año, permitiendo preveer con mayor precisión cúando habrá que comprar X material/alimento y la cantidad de productos que se pueden producir, evitando
¿De qué forma resuelve esto el problema?

2022-09-28 15:53 UTC, Gundisalvus2 commented
@JJ listo para revisión.

2022-09-28 17:53 UTC, JJ requested changes
Tendrías que especificar bastante más, para tener claro qué es lo que quieres hacer pero, sobre todo, para que sea suficientemente diferente del otro proyecto que va en esta dirección.

2022-09-28 17:53 UTC, JJ commented on README.md
> +Ya sea por desgana, desconocimiento o por imposibilidad, la mayoría de la gente no lleva una alimentación saludable. Por ello, se pretende crear una aplicación en la nube que sea accesible para todo
Basar un problema en cuestiones físicas en vez de procesamiento de información es arriesgado, para empezar. En caso de que facilite los hábitos, como no tienes retroalimientación, no vas a saber si se ha resuelto el problema o no.
Por favor, lee en las preguntas frecuentes del objetivo 0 lo que suele constituir un buen problema para resolver y qué no.

2022-09-28 17:53 UTC, JJ commented on README.md
> +Toda aquella persona que desee llevar una vida más saludable y que esté interesado en mejorar su alimentación.
No es suficientemente preciso, ni explica qué beneficio tiene *la aplicación* (no hacer lo que quiera que te aconseje la aplicación)

2022-09-29 16:38 UTC, Gundisalvus2 commented
@JJ Listo para revisión.

2022-09-29 18:03 UTC, JJ approved these changes
Sería conveniente que aclararas lo que te he comentado antes de fusionar o del siguiente objetivo.

2022-09-29 18:03 UTC, JJ commented on README.md
> +Ya sea por desgana, desconocimiento o por imposibilidad, la mayoría de la gente no lleva una alimentación saludable. Por ello, se pretende crear una aplicación en la nube que sea accesible para todo
Debes intentar modificar todos los textos a los que se refieran los comentarios. En este caso, definiendo mejor el problema que se va a tratar de solucionar.

2022-09-29 18:03 UTC, JJ commented on README.md
> +Toda aquella persona que desee llevar una vida más saludable y que esté interesado en mejorar su alimentación.
:arrow_up:

2022-09-30 08:19 UTC, Gundisalvus2 commented
@JJ listo para revisión

2022-09-30 11:35 UTC, JJ approved these changes
:+1:

2022-09-30 11:41 UTC, JJ commented
Ya estaba aprobado de todas formas, no tienes que ponerlo de nuevo para aprobar, simplemente haz los cambios para que estén listos en el objetivo siguiente

2022-10-04 15:53 UTC, merged

2022-10-16 07:47 UTC, JJ commented
Deberías haber entregado ya a estas alturas el objetivo 1. Por favor organízate bien el tiempo para poder superar los objetivos mínimos de la asignatura.